import type { Surah } from './types'

export const AVATAR_COLORS = [
  '#1D9E75', '#534AB7', '#BA7517', '#A32D2D',
  '#0F6E56', '#3C3489', '#633806', '#2D4EA3',
]

export const TARGET_JUZ = 5

export const NILAI_OPTIONS = [
  'Mumtaz',
  'Jayyid Jiddan',
  'Jayyid',
  'Maqbul',
  'Perlu Ulang',
]

export const ALL_SURAHS: Surah[] = [
  { no: 1, nama: 'Al-Fatihah', arab: 'الفاتحة', ayat: 7, juz: 1 },
  { no: 2, nama: 'Al-Baqarah (1-141)', arab: 'البقرة', ayat: 141, juz: 1 },
  { no: 3, nama: 'Al-Baqarah (142-252)', arab: 'البقرة', ayat: 111, juz: 2 },
  { no: 4, nama: 'Al-Baqarah (253-286)', arab: 'البقرة', ayat: 34, juz: 3 },
  { no: 5, nama: 'Ali Imran (1-92)', arab: 'آل عمران', ayat: 92, juz: 3 },
  { no: 6, nama: 'Ali Imran (93-200)', arab: 'آل عمران', ayat: 108, juz: 4 },
  { no: 7, nama: 'An-Nisa (1-23)', arab: 'النساء', ayat: 23, juz: 4 },
  { no: 8, nama: 'An-Nisa (24-147)', arab: 'النساء', ayat: 124, juz: 5 },
  { no: 9, nama: 'An-Nisa (148-176)', arab: 'النساء', ayat: 29, juz: 6 },
  { no: 10, nama: 'Al-Maidah (1-82)', arab: 'المائدة', ayat: 82, juz: 6 },
  { no: 11, nama: 'Al-Maidah (83-120)', arab: 'المائدة', ayat: 38, juz: 7 },
  { no: 12, nama: 'Al-An\'am (1-110)', arab: 'الأنعام', ayat: 110, juz: 7 },
  { no: 13, nama: 'Al-An\'am (111-165)', arab: 'الأنعام', ayat: 55, juz: 8 },
  { no: 14, nama: 'Al-A\'raf (1-87)', arab: 'الأعراف', ayat: 87, juz: 8 },
  { no: 15, nama: 'Al-A\'raf (88-206)', arab: 'الأعراف', ayat: 119, juz: 9 },
  { no: 16, nama: 'Al-Anfal', arab: 'الأنفال', ayat: 75, juz: 9 },
  { no: 17, nama: 'At-Taubah (1-93)', arab: 'التوبة', ayat: 93, juz: 10 },
  { no: 18, nama: 'At-Taubah + Yunus', arab: 'يونس', ayat: 109, juz: 11 },
  { no: 19, nama: 'Hud + Yusuf (1-52)', arab: 'هود', ayat: 52, juz: 12 },
  { no: 20, nama: 'Yusuf (53-111) + Ar-Ra\'d', arab: 'يوسف', ayat: 59, juz: 13 },
  { no: 21, nama: 'Ibrahim + Al-Hijr', arab: 'إبراهيم', ayat: 99, juz: 13 },
  { no: 22, nama: 'An-Nahl', arab: 'النحل', ayat: 128, juz: 14 },
  { no: 23, nama: 'Al-Isra + Al-Kahfi (1-74)', arab: 'الإسراء', ayat: 111, juz: 15 },
  { no: 24, nama: 'Al-Kahfi (75-110) + Maryam', arab: 'الكهف', ayat: 98, juz: 16 },
  { no: 25, nama: 'Ta-Ha + Al-Anbiya', arab: 'طه', ayat: 135, juz: 17 },
  { no: 26, nama: 'Al-Hajj + Al-Mu\'minun', arab: 'الحج', ayat: 78, juz: 17 },
  { no: 27, nama: 'An-Nur + Al-Furqan', arab: 'النور', ayat: 64, juz: 18 },
  { no: 28, nama: 'An-Naml + Al-Qasas', arab: 'النمل', ayat: 93, juz: 19 },
  { no: 29, nama: 'Al-Ankabut + Ar-Rum + Luqman', arab: 'العنكبوت', ayat: 69, juz: 20 },
  { no: 30, nama: 'Al-Ahzab + Saba', arab: 'الأحزاب', ayat: 73, juz: 21 },
  { no: 31, nama: 'Ya-Sin + As-Saffat + Sad', arab: 'يس', ayat: 83, juz: 22 },
  { no: 32, nama: 'Az-Zumar + Ghafir', arab: 'الزمر', ayat: 75, juz: 23 },
  { no: 33, nama: 'Fussilat + Asy-Syura + Az-Zukhruf', arab: 'فصلت', ayat: 54, juz: 24 },
  { no: 34, nama: 'Al-Ahqaf + Muhammad + Al-Fath', arab: 'الأحقاف', ayat: 35, juz: 25 },
  { no: 35, nama: 'Az-Zariyat s.d. Al-Hadid', arab: 'الذاريات', ayat: 60, juz: 26 },
  { no: 36, nama: 'Al-Mujadilah s.d. At-Tahrim', arab: 'المجادلة', ayat: 22, juz: 27 },
  { no: 37, nama: 'Al-Mulk s.d. Al-Mursalat', arab: 'الملك', ayat: 30, juz: 28 },
  { no: 38, nama: 'An-Naba\' s.d. Al-Infitar', arab: 'النبأ', ayat: 40, juz: 29 },
  { no: 39, nama: 'Al-Mutaffifin s.d. Al-Buruj', arab: 'المطففين', ayat: 36, juz: 29 },
  { no: 40, nama: 'At-Tariq', arab: 'الطارق', ayat: 17, juz: 30 },
  { no: 41, nama: 'Al-A\'la', arab: 'الأعلى', ayat: 19, juz: 30 },
  { no: 42, nama: 'Al-Ghasyiyah', arab: 'الغاشية', ayat: 26, juz: 30 },
  { no: 43, nama: 'Al-Fajr', arab: 'الفجر', ayat: 30, juz: 30 },
  { no: 44, nama: 'Al-Balad', arab: 'البلد', ayat: 20, juz: 30 },
  { no: 45, nama: 'Asy-Syams', arab: 'الشمس', ayat: 15, juz: 30 },
  { no: 46, nama: 'Al-Lail', arab: 'الليل', ayat: 21, juz: 30 },
  { no: 47, nama: 'Ad-Duha', arab: 'الضحى', ayat: 11, juz: 30 },
  { no: 48, nama: 'Al-Insyirah', arab: 'الشرح', ayat: 8, juz: 30 },
  { no: 49, nama: 'At-Tin', arab: 'التين', ayat: 8, juz: 30 },
  { no: 50, nama: 'Al-Alaq', arab: 'العلق', ayat: 19, juz: 30 },
  { no: 51, nama: 'Al-Qadr', arab: 'القدر', ayat: 5, juz: 30 },
  { no: 52, nama: 'Al-Bayyinah', arab: 'البينة', ayat: 8, juz: 30 },
  { no: 53, nama: 'Az-Zalzalah', arab: 'الزلزلة', ayat: 8, juz: 30 },
  { no: 54, nama: 'Al-Adiyat', arab: 'العاديات', ayat: 11, juz: 30 },
  { no: 55, nama: 'Al-Qari\'ah', arab: 'القارعة', ayat: 11, juz: 30 },
  { no: 56, nama: 'At-Takatsur', arab: 'التكاثر', ayat: 8, juz: 30 },
  { no: 57, nama: 'Al-Asr', arab: 'العصر', ayat: 3, juz: 30 },
  { no: 58, nama: 'Al-Humazah', arab: 'الهمزة', ayat: 9, juz: 30 },
  { no: 59, nama: 'Al-Fil', arab: 'الفيل', ayat: 5, juz: 30 },
  { no: 60, nama: 'Quraisy', arab: 'قريش', ayat: 4, juz: 30 },
  { no: 61, nama: 'Al-Ma\'un', arab: 'الماعون', ayat: 7, juz: 30 },
  { no: 62, nama: 'Al-Kautsar', arab: 'الكوثر', ayat: 3, juz: 30 },
  { no: 63, nama: 'Al-Kafirun', arab: 'الكافرون', ayat: 6, juz: 30 },
  { no: 64, nama: 'An-Nasr', arab: 'النصر', ayat: 3, juz: 30 },
  { no: 65, nama: 'Al-Masad', arab: 'المسد', ayat: 5, juz: 30 },
  { no: 66, nama: 'Al-Ikhlas', arab: 'الإخلاص', ayat: 4, juz: 30 },
  { no: 67, nama: 'Al-Falaq', arab: 'الفلق', ayat: 5, juz: 30 },
  { no: 68, nama: 'An-Nas', arab: 'الناس', ayat: 6, juz: 30 },
]
